# Generated by Django 4.0.3 on 2022-03-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_public',
            new_name='public',
        ),
    ]
